# ---Environment Configs---
defaults:
  - _self_
  - scenario: con-7x7x5a # [con-5x5x3a, con-7x7x5a, con-10x10x5a, con-15x15x10a]
# Further environment config details in "con-10x10x5a" file.

env_name: MaConnector # Used for logging purposes.

# Defines the metric that will be used to evaluate the performance of the agent.
# This metric is returned at the end of an experiment and can be used for hyperparameter tuning.
eval_metric: episode_return

# Whether the environment observations encode implicit agent IDs. If True, the AgentID wrapper is not used.
# This should not be changed.
implicit_agent_id: True

kwargs:
  time_limit: 100
